global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'mantaro'
    
    file_sd_configs:
      - files: ['/etc/prometheus/mantaro.json']

  - job_name: 'mantaro-patreon'
    file_sd_configs:
      - files: ['/etc/prometheus/patreon.json']
